version: '2.1'

volumes:
  db-data:
  vendor:
  var:

services:
  moje_pliki:
    image: teravista/be_188555
    build:
        context: .
        dockerfile: dockerfile
    environment:
      DISABLE_MAKE: 0
      PS_INSTALL_AUTO: 1
      DB_PASSWD: student
      DB_NAME: BE_188555
      DB_USER: root
      DB_SERVER: db
      DB_PREFIX: ps_
      PS_DOMAIN: localhost:8001
      PS_FOLDER_INSTALL: ${PS_FOLDER_INSTALL:-install-dev}
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN:-admin-dev}
      PS_COUNTRY: ${PS_COUNTRY:-pl}
      PS_LANGUAGE: ${PS_LANGUAGE:-pl}
      PS_DEV_MODE: ${PS_DEV_MODE:-1}
      PS_ENABLE_SSL: ${PS_ENABLE_SSL:-0}
      PS_ERASE_DB: ${PS_ERASE_DB:-0}
      ADMIN_MAIL: ${ADMIN_MAIL:-demo@prestashop.com}
      ADMIN_PASSWD: ${ADMIN_PASSWD:-Correct Horse Battery Staple}
    ports:
      - "8001:80"
      - "8002:443"
